@extends('layouts.admin')
@section('title',isset($vehicle)?'Aracı düzenle':'Araç ekle') @section('page_title',isset($vehicle)?'Aracı düzenle':'Araç ekle')
@section('content')
<form method="post" action="{{ isset($vehicle)?route('admin.vehicles.update',$vehicle):route('admin.vehicles.store') }}" class="card"><div class="card-body">@csrf @isset($vehicle) @method('PUT') @endisset
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Plaka *</label><input class="form-control" name="plaka" required value="{{ old('plaka',$vehicle->plaka??'') }}"></div><div class="col-md-4"><label class="form-label">Marka *</label><input class="form-control" name="marka" required value="{{ old('marka',$vehicle->marka??'') }}"></div><div class="col-md-4"><label class="form-label">Model/tip *</label><input class="form-control" name="model" required value="{{ old('model',$vehicle->model??'') }}"></div><div class="col-md-3"><label class="form-label">Model yılı</label><input type="number" class="form-control" name="model_yili" value="{{ old('model_yili',$vehicle->model_yili??'') }}"></div><div class="col-md-3"><label class="form-label">Güncel km *</label><input type="number" class="form-control" name="guncel_km" required value="{{ old('guncel_km',$vehicle->guncel_km??0) }}"></div><div class="col-md-3"><label class="form-label">Renk</label><input class="form-control" name="renk" value="{{ old('renk',$vehicle->renk??'') }}"></div><div class="col-md-3"><label class="form-label">Yakıt</label><input class="form-control" name="yakit_cinsi" value="{{ old('yakit_cinsi',$vehicle->yakit_cinsi??'') }}"></div>
<div class="col-md-4"><label class="form-label">Sahip</label><select class="form-select" name="sahip_party_id"><option value="">—</option>@foreach($parties as $party)<option value="{{ $party->id }}" @selected(old('sahip_party_id',$vehicle->sahip_party_id??null)==$party->id)>{{ $party->ad }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Şase no</label><input class="form-control" name="sase_no" value="{{ old('sase_no',$vehicle->sase_no??'') }}"></div><div class="col-md-4"><label class="form-label">Motor no</label><input class="form-control" name="motor_no" value="{{ old('motor_no',$vehicle->motor_no??'') }}"></div>
<div class="col-md-3"><label class="form-label">Sonraki bakım km</label><input type="number" class="form-control" name="sonraki_bakim_km" value="{{ old('sonraki_bakim_km',$vehicle->sonraki_bakim_km??'') }}"></div>@foreach(['sonraki_bakim_tarihi'=>'Bakım tarihi','sonraki_muayene_tarihi'=>'Muayene tarihi','sigorta_bitis_tarihi'=>'Sigorta bitişi'] as $field=>$label)<div class="col-md-3"><label class="form-label">{{ $label }}</label><input type="date" class="form-control" name="{{ $field }}" value="{{ old($field,isset($vehicle)&&$vehicle->$field?$vehicle->$field->format('Y-m-d'):'') }}"></div>@endforeach
<div class="col-12"><label class="form-label">Donanımlar (virgülle ayırarak yaz, istediğin kadar serbest etiket ekleyebilirsin)</label><input class="form-control" name="donanimlar_csv" value="{{ old('donanimlar_csv', implode(', ', $vehicle->donanimlar ?? [])) }}" placeholder="Klima, ABS, Elektrikli cam, 5 İleri Manuel Şanzıman ..."></div><div class="col-md-6"><label class="form-label">Önceki sahipler notu</label><textarea class="form-control" name="onceki_sahipler_notu">{{ old('onceki_sahipler_notu',$vehicle->onceki_sahipler_notu??'') }}</textarea></div><div class="col-md-6"><label class="form-label">İç notlar</label><textarea class="form-control" name="notlar">{{ old('notlar',$vehicle->notlar??'') }}</textarea></div><div class="col-12"><label class="form-label">Vitrin açıklaması (herkese açık, ilan metni)</label><textarea class="form-control" rows="4" name="vitrin_aciklama" maxlength="4000">{{ old('vitrin_aciklama',$vehicle->vitrin_aciklama??'') }}</textarea></div>
@isset($vehicle)<div class="col-md-6"><label class="form-label">Km düşürülüyorsa düzeltme nedeni</label><textarea class="form-control" name="km_duzeltme_nedeni" placeholder="Eski: {{ $vehicle->guncel_km }} km"></textarea></div>@endisset<div class="col-md-6 form-check mt-5"><input type="hidden" name="vitrin_acik" value="0"><input class="form-check-input" type="checkbox" name="vitrin_acik" value="1" @checked(old('vitrin_acik',$vehicle->vitrin_acik??false))><label class="form-check-label">Herkese açık vitrini aç</label></div></div></div><div class="card-footer"><button class="btn btn-primary">Kaydet</button></div></form>
@endsection
